name = "developer-toolbox"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".open-next/assets"

[placement]
mode = "smart"

[ai]
binding = "AI"

[vars]
NEXT_PUBLIC_APP_URL = "https://devtools.catiteo.com"
NEXT_PUBLIC_APP_NAME = "DevToolbox"
